name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Har kuni ishga tushadi
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repozitoriyani yuklab olish
        uses: actions/checkout@v3

      - name: Snake animatsiyasini yaratish
        uses: Platane/snk@v3
        with:
          github_user_name: menacedjava
          outputs: dist/snake.svg

      - name: Output branchga push qilish
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout output || git checkout -b output
          mv dist/snake.svg snake.svg
          git add snake.svg
          git commit -m "Snake animatsiyasi yangilandi" || echo "Hech qanday o'zgarish yo'q"
          git push origin output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
