name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create output directory
        run: mkdir -p dist

      - name: Generate Snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: menacedjava
          outputs: dist/snake.svg

      - name: Push to output branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout output || git checkout -b output
          mv dist/snake.svg snake.svg
          git add snake.svg
          git commit -m "Updated Snake animation" || echo "No changes"
          git push origin output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
